Data instansi
FaruqRahmadani/Aplikasi_E-Bansos pull request #7
Opened 2018-03-15 15:52 UTC by FaruqRahmadani

# Yang di gawi
Semua menu di Daftar Instansi

# Jalankannya
- refresh migrate dan seed ulang

# gambar2
![image](https://user-images.githubusercontent.com/11961119/37474613-bb4cbf70-28ab-11e8-8f53-3a03b1822774.png)
![image](https://user-images.githubusercontent.com/11961119/37474633-cb1c0758-28ab-11e8-90a0-20fcdd90485f.png)
![image](https://user-images.githubusercontent.com/11961119/37474675-e662733a-28ab-11e8-97dc-cab23c9de513.png)
![image](https://user-images.githubusercontent.com/11961119/37474701-f49b4670-28ab-11e8-89b7-0c85c0d4e67c.png)

2018-03-19 14:04 UTC, syauqiahmd approved these changes
acc

2018-03-19 14:06 UTC, syauqiahmd requested changes
simpan pada edit data

2018-03-22 12:32 UTC, FaruqRahmadani commented
ada apa tu qi?

2018-03-24 02:52 UTC, FaruqRahmadani commented
diwadah ku lancar aja semuaan, coba clear cache qi

2018-03-28 17:31 UTC, syauqiahmd commented
penambahan detailing 
![screen shot 2018-03-29 at 1 28 07 am](https://user-images.githubusercontent.com/35471602/38045965-ec99c1c8-32f0-11e8-8772-8e75cbe5560e.png)

selebihnya sudah ok 👌🏻

2018-04-01 01:29 UTC, FaruqRahmadani commented
**Updated** info data pemohon

![image](https://user-images.githubusercontent.com/11961119/38168962-250b2b0a-358f-11e8-827b-b2a94838e787.png)

2018-04-02 15:00 UTC, merged